project/auth.py
import os

from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required

from .models import User
from .forms import LoginForm, NewUserForm
from . import db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        user = User.query.filter_by(email=login_form.email.data).first()
        password = login_form.password.data

        if not user or not check_password_hash(user.password, password):
            flash("Please check your login details and try again.")
            # if the user doesn't exist or password is wrong, reload the page
            return redirect(url_for("auth.login"))

        # if the above check passes, then we know the user has the right credentials
        remember = login_form.remember.data
        login_user(user, remember=remember)
        return redirect(url_for("main.index"))
    return render_template("login.html", form=login_form)


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    # Set form as none if users are to be invited since the project is very very small.
    # nform = None
    nform = NewUserForm()
    if nform.validate_on_submit():
        # If user's email already exists
        if User.query.filter_by(email=nform.email.data).first():
            # Send flash messsage
            flash("You've already signed up with that email, log in instead!")
            # Redirect to /login route.
            return redirect(url_for("auth.login"))

        hash_and_salted_password = generate_password_hash(
            nform.password.data, method="pbkdf2:sha256", salt_length=8
        )
        new_user = User(
            email=nform.email.data,
            name=nform.name.data,
            password=hash_and_salted_password,
            # No need to convert to json
            device_options={},
        )
        db.session.add(new_user)
        db.session.commit()

        # Logging in right after registering so the user can access the
        # full page
        login_user(new_user)

        return redirect(url_for("main.index"))
    if request.method == "POST":
        # Send flash messsage
        flash("Error, check the submitted data, did you confirm your password?")
    return render_template(
        "signup.html", info_email=os.environ.get("INFO_EMAIL"), form=nform
    )


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

project/views.py
import os
from project.models import Device, User
from project.forms import NewDeviceForm
from flask import Blueprint, redirect, render_template, request, url_for, jsonify, flash
from flask_login import login_required, current_user
from sqlalchemy.orm.attributes import flag_modified
from datetime import datetime
from . import db
from .prj_helper import select_from_all, update_user_dev_options

main = Blueprint("main", __name__)


INFO_EMAIL = os.environ.get("INFO_EMAIL")


@main.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        try:
            req_di = int(request.form["di"])
            req_ai = int(request.form["ai"])
            req_do = int(request.form["do"])
            req_ao = int(request.form["ao"])
        except Exception as e:
            msg = "One or more of your inputs are not a number between 0 and 128"
            flash(msg)
        else:
            devices = Device.query.order_by(Device.dev_type.asc(), Device.name.asc())

            if not next(item for item in devices if item.dev_type == "controller"):
                msg = "There are no CONTROLLERS available for use in the database, register to use your personal selection of devices."
                flash(msg)
                return render_template("index.html")

            # Get list of devices to evaluate
            if current_user.is_authenticated:
                user = User.query.get(current_user.id)
                user_device_options = update_user_dev_options(
                    devices, user.device_options
                )
                d2u = [
                    d["name"]
                    for d in user_device_options["devices"]
                    if d["select_user"]
                ]

                dquery = Device.query.filter(Device.name.in_(d2u)).order_by(
                    Device.dev_type.asc(), Device.name.asc()
                )
                devices_to_use = [d.to_dict() for d in dquery]

            else:
                devices_to_use = [d.to_dict() for d in devices if d.is_default]

            selected = select_from_all(req_di, req_ai, req_do, req_ao, devices_to_use)
            return render_template(
                "index.html",
                selected=selected,
                req_di=req_di,
                req_ai=req_ai,
                req_do=req_do,
                req_ao=req_ao,
            )

    return render_template("index.html")


@main.route("/device_preferences")
@login_required
def device_preferences():
    devices = Device.query.order_by(Device.dev_type.asc(), Device.name.asc())
    user = User.query.get(current_user.id)
    user.device_options = update_user_dev_options(devices, user.device_options)
    flag_modified(user, "device_options")
    db.session.commit()
    return render_template(
        "device_selection.html", devices=user.device_options["devices"]
    )


@main.route("/man-dev", methods=["GET", "POST"])
@login_required
def manage_devices():
    # Display ascending order first by type then by name
    devices = Device.query.order_by(Device.dev_type.asc(), Device.name.asc())
    return render_template("managedevices.html", info_email=INFO_EMAIL, devices=devices)


@main.route("/new-dev", methods=["GET", "POST"])
@login_required
def add_device():
    new_device_form = NewDeviceForm()
    if new_device_form.errors:
        print(new_device_form.errors)
    # TODO:handle devices with same name
    if new_device_form.validate_on_submit():
        # print("this was a post request")
        new_device = Device(
            name=new_device_form.name.data,
            dev_type=new_device_form.dev_type.data,
            di=new_device_form.di.data,
            ai=new_device_form.ai.data,
            ui=new_device_form.ui.data,
            do=new_device_form.do.data,
            ao=new_device_form.ao.data,
            co=new_device_form.co.data,
            has_clock=new_device_form.has_clock.data,
            price=new_device_form.price.data,
            date_created=datetime.utcnow(),
            date_modified=datetime.utcnow(),
            user_created=current_user.name,
            user_modified=current_user.name,
        )
        # print("generated new device, trying to add")
        # print('trying to create a new device')
        db.session.add(new_device)
        db.session.commit()
        # print("this should be enough, it should have committed")
        return redirect(url_for("main.manage_devices"))
    # print("this was a get request")
    return render_template(
        "newdevice.html", info_email=INFO_EMAIL, form=new_device_form
    )


@main.route("/edit-device/<int:dev_id>", methods=["GET", "POST"])
@login_required
def edit_device(dev_id):
    device = Device.query.get(dev_id)
    edit_form = NewDeviceForm(
        name=device.name,
        dev_type=device.dev_type,
        di=device.di,
        ai=device.ai,
        ui=device.ui,
        do=device.do,
        ao=device.ao,
        co=device.co,
        has_clock=str(device.has_clock),
        price=device.price,
    )

    # if edit_form.is_submitted():
    #     print("submitted")
    #     print(edit_form.errors)

    # if edit_form.validate():
    #     print("valid")

    if edit_form.validate_on_submit():
        # print("Validated submission")
        device.dev_type = edit_form.dev_type.data
        device.di = edit_form.di.data
        device.ai = edit_form.ai.data
        device.ui = edit_form.ui.data
        device.do = edit_form.do.data
        device.ao = edit_form.ao.data
        device.co = edit_form.co.data
        device.has_clock = edit_form.has_clock.data
        device.price = edit_form.price.data
        device.user_modified = current_user.name
        device.date_modified = datetime.utcnow()
        # print("trying to commit changes")
        db.session.commit()
        # print("Done, yay")
        return redirect(url_for("main.manage_devices"))

    return render_template(
        "editdevice.html",
        form=edit_form,
        dev_id=dev_id,
        dev_name=device.name.upper(),
        created_date=device.date_created.replace(microsecond=0).isoformat(),
        created_by=device.user_created,
        modified_date=device.date_modified.replace(microsecond=0).isoformat(),
        modified_by=device.user_modified,
    )


@main.route("/about")
@login_required
def about():
    return render_template("about.html", info_email=INFO_EMAIL)


@main.route("/test", methods=["GET"])
def my_test():
    ln = ["SNC25151", "PCX1711", "F4CGM", "SNC16121", "jajaja"]

    query = Device.query.filter(Device.name.in_(ln)).order_by(
        Device.dev_type.asc(), Device.name.asc()
    )

    for d in query:
        print(d.to_dict())
    return "you called?"


# @main.route("/delete/<int:device_id>")
# @login_required
# def delete_device(device_id):
#     device_to_delete = Device.query.get(device_id)
#     db.session.delete(device_to_delete)
#     db.session.commit()
#     return redirect(url_for("main.manage_devices"))

project/templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="wrapper">


  <!-- Page Content -->
  <div id="content-about">
    <!-- We'll fill this with dummy content -->
    <p>Report your issues to the following email: {{info_email}} </p>
  </div>

</div>



{% endblock %}

project/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
  <link rel="stylesheet" type="text/css" href="/static/styles.css">
  <title>Ctrl App</title>
</head>

<body class="d-flex flex-column min-vh-100">
  {% include "navbar.html" %}

  {% block content %}
  {% endblock %}

  {% include "footer.html" %}

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script> -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  <script src="{{ url_for('static',filename='toggle-price.js') }}"></script>

  {% block scripts %}
  <!-- Optional JavaScript -->
  {% endblock scripts %}
</body>

</html>

project/templates/device_selection.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="single-cont-center flex-fill">
    <h4 class="py-2">Device preference list</h4>
    {% if not devices %}
    <hr>
    <h4>There are no devices registered yet</h4>
    {% else %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col" class="text-center">Device</th>
          <th scope="col" class="text-center">Personal</th>
          <th scope="col" class="text-center">Global</th>
        </tr>
      </thead>
      <tbody>
        {% for d in devices %}
        <tr>
          <th scope="row">{{d['name']}}</th>
          <td>
            <!-- User preference -->
            <div class="custom-control custom-switch">
              <form class="text-center">
                {% if d['select_user'] %}
                <input type="checkbox" checked class="custom-control-input switch-device-user" id="user_{{d['name']}}">
                {% else %}
                <input type="checkbox" class="custom-control-input switch-device-user" id="user_{{d['name']}}">
                {% endif %}
                <label class="custom-control-label mx-0" for="user_{{d['name']}}"></label>
              </form>
            </div>
          </td>
          <td>
            <!-- Default/global preference -->
            <div class="custom-control custom-switch">
              <form class="text-center">
                {% if d['select_default'] %}
                <input type="checkbox" checked class="custom-control-input switch-device-global"
                  id="global_{{d['name']}}">
                {% else %}
                <input type="checkbox" class="custom-control-input switch-device-global" id="global_{{d['name']}}">
                {% endif %}
                <label class="custom-control-label mx-0" for="global_{{d['name']}}"></label>
              </form>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static',filename='toggle-device-global.js') }}"></script>
<script src="{{ url_for('static',filename='toggle-device-user.js') }}"></script>
{% endblock scripts %}

project/templates/editdevice.html
{% extends "base.html" %}
{% block content %}
<!-- Edit device form -->
<div class="d-flex justify-content-center">
  <div class="single-cont-center flex-fill">
    <div class="card mt-3">
      <div class="card-header text-white text-center">
        <strong>Edit "{{dev_name}}"</strong>
      </div>
      <div class="card-body">
        <form method="POST" action="/edit-device/{{dev_id}}">
          {{ form.csrf_token }}
          <div class="form-group d-none">
            {{form.name.label(class='mb-0')}}
            {{ form.name(class='form-control', placeholder='Device Name') }}
          </div>
          <div class="form-group">
            {{form.dev_type.label(class='mb-0')}}
            {{ form.dev_type(class='form-control') }}
          </div>
          <div class="form-group">
            {{form.di.label(class='mb-0')}}
            {{ form.di(class='form-control', type='number') }}
          </div>
          <div class="form-group">
            {{form.ai.label(class='mb-0')}}
            {{ form.ai(class='form-control', type='number') }}
          </div>
          <div class="form-group">
            {{form.ui.label(class='mb-0')}}
            {{ form.ui(class='form-control', type='number') }}
          </div>
          <div class="form-group">
            {{form.do.label(class='mb-0')}}
            {{ form.do(class='form-control', type='number') }}
          </div>
          <div class="form-group">
            {{form.ao.label(class='mb-0')}}
            {{ form.ao(class='form-control', type='number') }}
          </div>
          <div class="form-group">
            {{form.co.label(class='mb-0')}}
            {{ form.co(class='form-control', type='number') }}
          </div>
          <div class="form-group">
            {{form.has_clock.label(class='mb-0')}}
            {{form.has_clock(class='form-control') }}
          </div>
          <div class="form-group">
            {{form.price.label(class='mb-0')}}
            {{ form.price(class='form-control') }}
          </div>
          <div class="float-right">
            {{ form.submit(class='btn btn-success', value='Save changes') }}
          </div>
        </form>
      </div>
      <div class="card-footer text-muted">
        <p class="my-0"><em>{{dev_name}}</em></p>
        <p class="my-0"><em>Created on <span id="date-created">{{created_date}}</span> by {{created_by}}</em></p>
        <p class="my-0"><em>Modified on <span id="date-modified">{{modified_date}}</span> by {{modified_by}}</em></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static',filename='date-to-local.js') }}"></script>
{% endblock scripts%}

project/templates/footer.html
<!-- Footer -->
<div class="wrapper flex-grow-1"></div>
<footer class="container-fluid py-2 navbar-fixed-bottom">
  <hr class="myhr my-1">
  <div class="text-center text-black-50">
    Copyright © Ivan Bautista <span id="cdate">2020</span>
  </div>
  <div class="text-center text-black-50">
    Find the code on my
    <a href="https://github.com/ivanbaug/dc-ctrls" class="text-black-50"> GitHub
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github icon-link"
        viewBox="0 0 16 16">
        <path
          d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
      </svg>
    </a>
  </div>
</footer>
<!-- Auto update year -->
<script type="text/javascript">
  document.getElementById("cdate").innerHTML = new Date().getFullYear();
</script>

project/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="single-cont-center flex-fill">
    <!-- Main form -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <form action="{{url_for('main.index')}}" method="post" class="pt-5 w-100">
      <div class="card">
        <div class="card-header text-white text-center">
          <strong>REQUIRED I/O's</strong>
        </div>
        <div class="card-body">
          <div class="d-flex justify-content-around">
            <div class="io-input-box px-2 text-center">
              <p class="my-1"><b>di</b></p>
              <input class="form-control " type="number" name="di" min="0" max="128" value={{req_di if req_di else 0}}
                onClick="this.select();">
            </div>
            <div class="io-input-box px-2 text-center">
              <p class="my-1"><b>ai</b></p>
              <input class="form-control " type="number" name="ai" min="0" max="128" value={{req_ai if req_ai else 0}}
                onClick="this.select();">
            </div>
            <div class="io-input-box px-2 text-center">
              <p class="my-1"><b>do</b></p>
              <input class="form-control " type="number" name="do" min="0" max="128" value={{req_do if req_do else 0}}
                onClick="this.select();">
            </div>
            <div class="io-input-box px-2 text-center">
              <p class="my-1"><b>ao</b></p>
              <input class="form-control " type="number" name="ao" min="0" max="128" value={{req_ao if req_ao else 0}}
                onClick="this.select();">
            </div>
          </div>
        </div>
      </div>
      <!-- TODO: a more dynamic button -->
      <div class="text-center my-3">
        <input type="submit" value="Enlighten me!" class="btn btn-outline-info btn-lg">
      </div>
    </form>
    {% if selected %}
    <!-- Display results -->
    <div class="alert alert-primary sticky-top" role="alert">
      Results for: {{req_di}} di | {{req_ai}} ai | {{req_do}} do | {{req_ao}} ao
    </div>
    {% for sel in selected %}
    <table class="table table-sm table-bordered mt-3 text-center">
      <tr class="table-head-custom-bg">
        <th class="text-left result-first-col">OP{{loop.index}}</th>
        <th>di</th>
        <th>ai</th>
        <th>ui</th>
        <th>do</th>
        <th>ao</th>
        <th>co</th>
      </tr>
      {% for m in sel['device_summary'] %}
      <tr>
        <td class="text-left result-first-col">{{m["name"]}}</td>
        <td>{{m["di"] | string}}</td>
        <td>{{m["ai"] | string}}</td>
        <td>{{m["ui"] | string}}</td>
        <td>{{m["do"] | string}}</td>
        <td>{{m["ao"] | string}}</td>
        <td>{{m["co"] | string}}</td>
      </tr>
      {% endfor %}
      {% if current_user.is_authenticated and current_user.show_prices %}
      <caption class="mx-2 pt-1">Price: ${{sel['cost']}}</caption>
      {% endif %}
    </table>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

project/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="single-cont-center flex-fill">
    <div class="card mt-5">
      <div class="card-header text-white text-center">
        <strong>USER DETAILS</strong>
      </div>
      <div class="card-body">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
          {{ form.csrf_token }}
          <div class="form-group">
            {{ form.email(class='form-control', placeholder='Your e-mail') }}
          </div>
          <div class="form-group">
            {{ form.password(class='form-control', placeholder='Password') }}
          </div>
          <div class="form-check">
            {{ form.remember(class='form-check-input', placeholder='Remember me') }}
            Remember me
          </div>
          <div class="float-right">
            {{ form.submit(class='btn btn-success') }}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

project/templates/managedevices.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="single-cont-center flex-fill">
    <h3 class="py-3">Device list</h3>
    {% if not devices %}
    <hr>
    <h4>There are no devices registered yet</h4>
    {% endif %}
    {% for d in devices %}
    <!-- TODO: implement modal for edit and delete forms/actions -->
    <div class="card my-3">
      <div class="card-header text-white text-center d-flex {{'card-header-exp' if d.dev_type == 'expansion'}}">
        <div class="mr-auto"><strong>{{d.name}}</strong></div>
        <!-- Price is optional -->
        {% if current_user.show_prices %}
        <div class="mx-2">Price: ${{d.price | int}}</div>
        {% endif %}
        <div class="mx-2">{{d.dev_type}}</div>
        {% if d.has_clock %}
        <div class="mx-2"><i class="bi bi-clock"></i></div>
        {% endif %}
      </div>
      <div class="container">
        <div class="row border py-1">
          <div class="col border-right">
            DI: {{d.di}}
          </div>
          <div class="col border-right">
            AI: {{d.ai}}
          </div>
          <div class="col">
            UI: {{d.ui}}
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row border py-1">
          <div class="col border-right">
            DO: {{d.do}}
          </div>
          <div class="col border-right">
            AO: {{d.ao}}
          </div>
          <div class="col">
            CO: {{d.co}}
          </div>
        </div>
      </div>
      <div class="btn-group " role="group" aria-label="Second group">
        <a href="{{url_for('main.edit_device',dev_id=d.id)}}" class="btn btn-outline-success btn-sm">
          <i class="bi bi-pencil mx-2"></i>Edit</a>
        <button type="button" class="btn btn-outline-danger btn-sm" data-device-id="{{d.id}}"
          data-device-name="{{d.name}}" data-toggle="modal" data-target="#modalDelete"> <i
            class="bi bi-trash mx-2"></i>Delete</button>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- Modals -->
<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit device</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...hi :)
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete device</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Please confirm you want to delete <strong><span name="deviceName">device_name</span></strong> PERMANENTLY.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="btnModalDelete">Delete</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static',filename='modal-delete.js') }}"></script>
{% endblock scripts %}

project/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark navbar-custom navbar-fixed-top">
  <a class="navbar-brand" href="{{ url_for('main.index') }}"> DVC Device Selector </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if current_user.is_authenticated %}
    <ul class="navbar-nav me-auto ">
      <li class="navbar-text pb-1"> Welcome back, {{current_user.name}}.</li>
    </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">

      {% if current_user.is_authenticated %}
      <li class="nav-item dropdown navbar-dark ">
        <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdown" role="button"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="bi bi-sliders" style="font-size: 1.3rem; "></i>
          <div class="ml-2">Settings</div>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-item" id="price-switch">
            <div class="custom-control custom-switch">
              <form>
                {% if current_user.show_prices %}
                <input type="checkbox" checked class="custom-control-input" id="cPriceSwitch">
                {% else %}
                <input type="checkbox" class="custom-control-input" id="cPriceSwitch">
                {% endif %}
                <label class="custom-control-label" for="cPriceSwitch">Show prices</label>
              </form>
            </div>
          </div>
          <a class="dropdown-item" href="{{url_for('main.add_device')}}">New Device</a>
          <a class="dropdown-item" href="{{url_for('main.manage_devices')}}">Manage devices</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ url_for('main.device_preferences') }}">Enable/disable devices</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex align-items-center" href="{{ url_for('main.device_preferences') }}">
          <i class="bi bi-person-circle" style="font-size: 1.3rem; color: rgb(216, 216, 216);"></i>
          <div class="ml-2">{{current_user.name}}'s Profile</div>
        </a>
      </li>
      {% endif %}
      {% if not current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link d-flex align-items-center" href="{{ url_for('auth.login') }}">
          <i class="bi bi-person-circle" style="font-size: 1.3rem; color: rgb(216, 216, 216);"></i>
          <div class="ml-2">Login</div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex align-items-center" href="{{ url_for('auth.signup') }}">
          <i class="bi bi-person-plus-fill" style="font-size: 1.3rem; color: rgb(216, 216, 216);"></i>
          <div class="ml-2">Signup</div>
        </a>
      </li>
      {% endif %}
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link d-flex align-items-center" href="{{ url_for('auth.logout') }}">
          <i class="bi bi-door-closed-fill" style="font-size: 1.3rem; color: rgb(216, 216, 216);"></i>
          <div class="ml-2">Logout</div>
        </a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav>